services:
  # permissionsapp.server:
  #   container_name: permissionsapp.server
  #   image: ${DOCKER_REGISTRY-}permissionsappapi
  #   build:
  #     context: ./src/PermissionsApp.Server
  #     dockerfile: Dockerfile
  #   depends_on:
  #     permissionsapp.database:
  #       condition: service_healthy
  #   networks:
  #     - app-network

  permissionsapp.webapi:
    container_name: permissionsapp.webapi
    image: ${DOCKER_REGISTRY-}permissionsappwebapi
    build:
      context: ./src/PermissionsApp.WebAPI
      dockerfile: Dockerfile
    depends_on:
      permissionsapp.database:
        condition: service_healthy
    networks:
      - app-network

  permissionsapp.react:
    container_name: permissionsapp.react
    build:
      context: ./src/PermissionsApp.React
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - app-network
  
  permissionsapp.database:
    container_name: permissionsapp.database
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
        - 1433:1433
    environment:
        ACCEPT_EULA: 'Y'
        SA_PASSWORD: 'SuperPassword123'
    volumes:
        - ./sqlserver/data:/var/opt/mssql/data
        - ./sqlserver/log:/var/opt/mssql/log
    healthcheck:
        test: /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P "SuperPassword123" -Q "SELECT 1" -b -o /dev/null
        interval: 10s
        timeout: 3s
        retries: 10
        start_period: 30s
    networks:
      - app-network

  zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    depends_on:
      - zookeeper
    networks:
      - app-network
  
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    networks:
      - app-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=SuperPassword123
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
    ports:
      - "9200:9200"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge